
name: Checks

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ["test", "lint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Run nox ${{ matrix.check }}
        run: |
          poetry install
          poetry run nox -rs ${{ matrix.check }}
