
name: Nox

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Nox
        uses: excitedleigh/setup-nox@v2.1.0
      - name: Run nox tests
        run: nox -rs test
