
name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
      - name: Run nox publish
        run: |
          poetry install
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --repository pypi
